### ISSUE TITLE
fails to compile with vala ≥ 0.53.1

### ISSUE THREAD

**Issue by decathorpe** [elementary/photos#638]
Both the latest released version and git master fail to compile since vala was updated to version 0.53.1 in Fedora 35 / Rawhide:

```
libgphoto2.vapi:315.9-315.29: error: [SimpleType] struct `GPhoto.CameraStorageInformation' cannot have owned heap-allocated fields
        public string basedir;
        ^^^^^^^^^^^^^^^^^^^^^
libgphoto2.vapi:177.9-177.26: error: [SimpleType] struct `GPhoto.CameraFileInfoPreview' cannot have owned heap-allocated fields
        public string type;
        ^^^^^^^^^^^^^^^^^^
libgphoto2.vapi:160.9-160.26: error: [SimpleType] struct `GPhoto.CameraFileInfoFile' cannot have owned heap-allocated fields
        public string type;
        ^^^^^^^^^^^^^^^^^^
```

Not sure if this is an actual issue in vala 0.53.1, elementary Photos, or a problem with libgphotos2, as the file where the error occurs suggests. The only other package in Fedora that now fails with a comparable error message is shotwell (which elementary Photos has been forked off from?), where both `libraw.vapi` and `libgphoto2.vapi` have this "cannot have owned heap-allocated fields" problem.

**Comment by davidmhewitt** [comment]
@decathorpe I marked my PR as "fixes" for this since I compiled and tested the changes on Fedora 35. So this should be good.

But it's interesting that your original comment here says that Shotwell is failing with the same errors. I took the updated vapi files that fixed this from Shotwell. So I guess there's an older release being built in Fedora that doesn't contain those fixes yet? Or it's already fixed!

Anyway, feel free to re-open if I somehow haven't fixed this!

**Comment by decathorpe** [comment]
Looks like the shotwell package in Fedora cherry-picked similar fixes from upstream here:
https://src.fedoraproject.org/rpms/shotwell/c/9f679a2daede20fc64c88e2e270c7f384d87c593?branch=rawhide

Anyway, the linked PR fixes the problem, so it's all good from my side. :100:
